In [ ]:
'''
作業目標
活用矩陣運算，實做線性代數
作業重點
線性代數公式應用
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:
array1 = np.array([[10, 8], [3, 5]])

運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?
'''

In [2]:
import numpy as np

In [4]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])
A = np.linalg.inv(array1)
print(A @ array1)

[[1. 0.]
 [0. 1.]]


In [6]:
#2. 運用上列array計算特徵值、特徵向量?
np.linalg.eig(array1)

(array([13.,  2.]),
 array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [8]:
#3. 運用上列array計算SVD?
np.linalg.matrix_rank(array1)

2